### PR TITLE
Swiss cheese

### PR DESCRIPTION
**Pull request by Filco306**
Added a `d`-dimensional swiss cheese with tests. I think we need to investigate its qualitites further, but it does its job. 

The cheese is a hypercube between -1 and 1 with small, randomized spheres in which points are not permitted. I think these can serve as interesting examples to clearly demonstrate Persistent Homology.

### CODE REVIEW

**Comment by Filco306** [comment]
We should probably wait with this one until #8 is merged.

**Comment by Filco306** [comment]
I think this is pretty cool 2d swiss cheese :D 

Skärmavbild 2020-11-16 kl  16 23 56

**Comment by ctralie** [comment]
Looks great!!

**Comment by Filco306** [comment]
Awesome! And by the way, I will do another modification here before merging this in. 

The radii of spheres in d dimensions increase by the number of dimensions. I did some amateur math the other day, and concluded some small stuff.

1. Assume a hypersphere in d dimensions, such that , then we have that . 
2. If we assume the case where  for a hypersphere with dimension d, the radius has to increase at the speed of . If we consider d = 2 as our basecase, it is suitable to multiply the sampling of the radii by , don't you think? 

Let me know your opinion on this; either way, I think I will add that quick modification here. 

Cheers!

**Comment by Filco306** [comment]
Actually, let me take all of that back, haha. This is harder than I thought; maintaining the ratio between a hypersphere and a hypercube is not that easy. Brb with some further analysis

**Comment by Filco306** [comment]
Hello! I have to work on this a little bit more I believe. I think a start is just to produce swiss cheeses for 2 and 3 dimensions. Let's leave it for higher dimensions for now; those are much more complicated I believe. 

Thank you!

**Comment by sauln** [comment]
@Filco306  sorry for disappearing on this PR.. What do you think, is it ready to go?  I've updated the deploy process, so it should be easy for us to get it out there when it's ready.  You'll have to merge master, fix the merge conflicts, and bump a new version (I think 0.3).

Let me know if you want to keep working on this, or get it out and then create a new PR for more upgrades?

**Comment by Filco306** [comment]
Hello again @sauln , 

I think I want to redo this one and wait for another. I will close this PR and get back to you with a new one. 

In short, the problem is the combination of hypersquares and hyperspheres. Combining these make the relation between the volume of the holes and the entire surface tend to infinity, which more or less removes the holes. I will either do a swiss cheese with hypercube holes or hyperspheres with hyperspheres holes, not the two combined :) 

Again, sorry for my late reply here!

**Comment by Filco306** [comment]
One thing I can do however is to generate 2d- and 3d-swiss cheeses. In just 2 or 3 dimensions, the combination does work :)

**Pull request closed without merging**
